### ISSUE TITLE
TypeError: save_image() missing 1 required positional argument: 'fp'

### ISSUE THREAD

**Issue by emnab** [laoreja/face-identity-transformer#8]
command: 
!CUDA_VISIBLE_DEVICES=0,1,2,3 python3 save_visual.py best.yaml --ckpt_name checkpoint_13_iter8193.pth.tar --dataset  LFW

error:
test_dataset: Dataset LFW
    Number of imgs: 48
    Root Location: data/lfw
    Transforms (if any): Compose(
                             Resize(size=(128, 128), interpolation=bicubic, max_size=None, antialias=True)
                             ToTensor()
                             Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
                         )

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
initialize network with normal
=> loading checkpoint 'checkpoint_13_iter8193.pth.tar'
=> loaded checkpoint 'checkpoint_13_iter8193.pth.tar' (epoch 13)
  0% 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/content/face-identity-transformer/save_visual.py", line 120, in <module>
    save_image((torch.cat((img[save_idx:save_idx + 1, ...].cpu(),
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: save_image() missing 1 required positional argument: 'fp'

**Comment by emnab** [comment]
solved:        
for save_idx in range(args.batch_size):
            save_image((torch.cat((img[save_idx:save_idx + 1, ...].cpu(),
                                   fake[save_idx:save_idx + 1, ...].cpu(),
                                   rand_fake[save_idx:save_idx + 1, ...].cpu(),
                                   wrong_recon[save_idx:save_idx + 1, ...].cpu(),
                                   recon[save_idx:save_idx + 1, ...].cpu(),), dim=0) + 1.) / 2.,
                       fp=osp.join(save_dir, '_'.join(img_path[save_idx].split('.')[0].split('/')[-2:]) + '.png'),
                       nrow=5,
                       padding=2,
                       pad_value=1)
